### ISSUE TITLE
[Front-end] Configurar projeto

### ISSUE THREAD

**Issue by olarclara** [DadosAbertosDeFeira/portal#11]
A proposta de tecnologia a ser usada é o [Next.js](https://nextjs.org/) por motivos de escalabilidade e performance, o fato do framework ser construído com [React](https://reactjs.org/) ajuda a diminuir a curva de aprendizado.

O próprio framework oferece uma utilidade para [configurar projetos](https://nextjs.org/docs/api-reference/create-next-app), sugiro que seja utilizada pra facilitar o processo.

O suporte a [Sass](https://sass-lang.com/) é [oferecido por padrão](https://sass-lang.com/), removendo a necessidade de configurações extras.

Sugiro que sejam adicionadas as rotas principais do projeto:
- / (home)
- /busca
- /sobre
- /colabore

**Comment by emersonsdo** [comment]
@anapaulagomes e @olarclara, posso pegar essa issue.

**Comment by emersonsdo** [comment]
É interessante já configurar o [eslint](https://eslint.org/docs/about/), ou seria uma complexidade que podemos deixar para depois?

**Comment by anapaulagomes** [comment]
Acho que os linters vão ser configurados na #12 com o CI. Talvez seja melhor ter uma issue separada para pre-commits também, aí podemos adicionar os linters localmente. O que acha @olarclara?

**Comment by olarclara** [comment]
@anapaulagomes  @emersonsdo eu acho que linters (eslint + prettier) podem ser configurados nessa tarefa, assim já temos essas regras desde o "hello, world".

**Comment by olarclara** [comment]
Marcando como feito pois o PR #17 do @emersonsdo foi mergeado! 🙌
