### ISSUE TITLE
Definir versão do node

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/portal#118]
Não consegui encontrar onde definimos a versão do node, posso estar cometendo um erro. :) Mas, no PR #107, o build estava falhando por utilizar uma versão incompatível com um dos plugins. A versão foi setada para 12.22.0 através de variável de ambiente (`NODE_VERSION`).
Seria bom termos isso no arquivo de configuração do Netlify e/ou numa configuração explícita no repositório.

**Comment by alvarogfn** [comment]
*Essa é a minha primeira vez tentando contribuir com open source.*

É possível configurar uma versão do node e do yarn a ser usada no projeto dentro do **package.json**:

https://classic.yarnpkg.com/lang/en/docs/package-json/#toc-engines

![image](https://user-images.githubusercontent.com/62889807/218171736-19bdfcab-eafe-4041-a406-1fc207f8ad01.png)

Mas o acredito que o netlify ainda não tem suporte para esse tipo de configuração, porque essa issue está aberta no repositório deles: https://github.com/netlify/build-image/issues/53.
