### ISSUE TITLE
[Front-end] Configurar Actions/CI/CD

### ISSUE THREAD

**Issue by olarclara** [DadosAbertosDeFeira/portal#12]
Idealmente teremos um ambiente de staging para validação, sugiro o uso de [GitHub Actions](https://github.com/features/actions) para acionar quaisquer _workflows_ necessários.

Adicionalmente, para checagem de performance, seo, acessibilidade e melhores práticas, podemos integrar o [Lighthouse](https://developers.google.com/web/tools/lighthouse?hl=pt_br) aos pull requests.

**Comment by gomex** [comment]
Essa tarefa está bloqueada por #29

**Comment by anapaulagomes** [comment]
Para essa tarefa precisamos pelo menos rodar os testes antes de fazer o deploy.

**Comment by gomex** [comment]
O deploy só será necessário se a ferramenta SaaS de hospedagem de front não faça isso. Se ela fizer, só teremos CI aqui.

**Comment by matheusrocha89** [comment]
Eu abri o PR #51 que faz rodar os testes antes de fazer deploy. Talvez isso já seja suficiente
