### ISSUE TITLE
[Front-end] Styleguide

### ISSUE THREAD

**Issue by olarclara** [DadosAbertosDeFeira/portal#13]
Essa tarefa pode ser dividida em sub-tarefas para acelerar o proceso de desenvolvimento. Adicionalmente, sugiro a configuração do [Storybook](https://storybook.js.org/) para compartilhamos o progresso e validarmos com os designers.

Idealmente, o styleguide deve incluir:

- Sistema de espaçamento - referência: https://spec.fm/specifics/8-pt-grid
- Breakpoints
- Sistema de cores (primária, secundária, _accent_, cinzas, texto, etc) #20 
- Tipografia (h1, h2, h3, paragráfos, itálicos, negritos, etc) (#21)
- Assets (Logo, personagens, etc)
- Ícones - referência: https://google.github.io/material-design-icons/
- Links (inclusos estados como hover e ativo)
- Botões (inclusos estados como hover e ativo)
- Inputs
    - Texto
    - Textareas
    - Select / dropdown
- Breadcrumbs
- Conteúdo flexível

Como nota, o processo de desenvolvimento deve ser, sempre que possível, _mobile first_ para atender a crescente parcela da população que acessa a internet por smartphones. [Fonte](https://g1.globo.com/economia/tecnologia/noticia/2020/04/29/em-2018-quase-46-milhoes-de-brasileiros-ainda-nao-tinham-acesso-a-internet-aponta-ibge.ghtml)

**Comment by matheusrocha89** [comment]
@anapaulagomes @olarclara Dessas tasks quero começar a fazer os botões, o que acham?

**Comment by anapaulagomes** [comment]
Joga duro, @matheusrocha89!
