### ISSUE TITLE
[Front-end] Header

### ISSUE THREAD

**Issue by olarclara** [DadosAbertosDeFeira/portal#14]
Contempla o desenvolvimento do componente `Header` a ser utilizado globalmente pelo site:

**Mobile**

|Default|Busca habilitada|Reduzido|
|:-:|:-:|:-:|
|<img width="820" alt="Screen Shot 2020-11-14 at 11 48 17 AM" src="https://user-images.githubusercontent.com/24959348/99149846-4a9d9a00-266f-11eb-82c7-261065d1c27b.png">|<img width="819" alt="Screen Shot 2020-11-14 at 11 49 06 AM" src="https://user-images.githubusercontent.com/24959348/99149870-686aff00-266f-11eb-9b5d-d594884a7a56.png">|<img width="815" alt="Screen Shot 2020-11-14 at 11 49 43 AM" src="https://user-images.githubusercontent.com/24959348/99149880-7fa9ec80-266f-11eb-8064-f81783690d74.png">|

**Desktop**
|Default|
|:-:|
|<img width="873" alt="Screen Shot 2020-11-14 at 11 50 59 AM" src="https://user-images.githubusercontent.com/24959348/99149905-ab2cd700-266f-11eb-91b8-085a41ec9a9a.png">|

Tarefa depende de componentes do styleguide definidos na issue #13.

**Comment by filipebsmaia** [comment]
Esse modelo "default" não foi atualizado no figma na Página "MVP do Site"?
![image](https://user-images.githubusercontent.com/53981608/109431697-9722a080-79e6-11eb-895f-5af14fa8de19.png)

**Comment by anapaulagomes** [comment]
Estamos aguardando resposta de André e Nataly no Discord. @filipebsmaia :)

**Comment by anapaulagomes** [comment]
O header utilizado será o "Desktop-1" em "MVP do Site".
https://www.figma.com/file/XNfcVKFQLMcw4WzYB9srDs/DadosFeira?node-id=224%3A2144

**Comment by olarclara** [comment]
Finalizado pelo @filipebsmaia no PR: https://github.com/DadosAbertosDeFeira/portal/pull/36.
