### ISSUE TITLE
Adicionar página 404

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/portal#23]

**Comment by matheusrocha89** [comment]
Temos design para essa página? Procurei no Figma mas não encontrei

**Comment by anapaulagomes** [comment]
Ainda não, @matheusrocha89! @DadosAbertosDeFeira/design rola ver algo pra gente? 😬

**Comment by filipebsmaia** [comment]
Tomei a liberdade em fiz um modelinho da página 404, será que rola a gente integrar ela assim?
![image](https://user-images.githubusercontent.com/53981608/132538041-950259b2-5648-4886-8ccf-639eac2795a3.png)
![image](https://user-images.githubusercontent.com/53981608/132538116-9ad31c73-590d-4c26-9002-d158ece8b031.png)

**Comment by anapaulagomes** [comment]
Eu curti! Por mim tudo bem @filipebsmaia

**Comment by matheusrocha89** [comment]
Também achei bacana. E é bom que já tem o design para mobile e para desktop

**Comment by matheusrocha89** [comment]
@filipebsmaia como anda essa página 404? Precisa de ajuda?

**Comment by filipebsmaia** [comment]
Vou começar a fazer essa hoje, não tive tempo esse final de semana :/
