### ISSUE TITLE
Configurar Sentry

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/portal#24]
Atualmente usamos o Sentry no Maria Quitéria. Seria legal adicionar ao frontend também para fazermos um acompanhamento dos erros.
~A versão que usamos é gratuita por isso só permite um usuário. Mas o Sentry também oferece um plano grátis para projetos open source. Vou agilizar essa aplicação pra gente ter mais usuários por lá.~ Aplicação aprovada. Agora podemos configurar de boas. :)

**Comment by matheusrocha89** [comment]
Como já temos no Maria Quiteria, provavelmente já temos configurada uma conta com a organização do dados abertos feira criada e eu acho uma boa ideia centralizar tudo lá, se me adicionar a ela eu posso criar o projeto para o portal e configurar @anapaulagomes

**Comment by anapaulagomes** [comment]
Nós até conversamos e resolvemos não fazer pra priorizar outras coisas mas fica a vontade pra pegar essa aqui! Dei permissões pro teu e-mail daqui do Github. :)

**Comment by matheusrocha89** [comment]
Configurando o Sentry me deparei com essa issue aqui (consegui colocar para funcionar normal, mas encontrei isso na documentação do sentry para nextjs, vou pesquisar um pouco mais a fundo) https://github.com/vercel/next.js/issues/20487#issuecomment-753884085

**Comment by matheusrocha89** [comment]
@anapaulagomes consegue me adicionar no Netlify também, preciso configurar umas coisas lá para usar o sentry. Please 👼
