### ISSUE TITLE
Investigar um SaaS para deploy do portal

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/portal#29]
Algumas opções:

* Netlify https://www.netlify.com/with/nextjs/
* Vercel

**Comment by anapaulagomes** [comment]
@emersonsdo

**Comment by gomex** [comment]
Escopo da analise:

- Custo
- Facilidade no deploy
- Funcionalidades interessantes para QA (ambiente temporário a cada PR, por exemplo)

**Comment by gomex** [comment]
@anapaulagomes a funcionalidade de SSR é importante, se for, olha o que achei:

```
Server Side Rendering
Server-Side rendering, or SSR, is a huge win for Vercel, as it's just not really feasible with Netlify. On Vercel, you can deploy a server-side rendered Next.js application within minutes.
```

https://dev.to/maxniederman/netlify-vs-vercel-a-comparison-5643

**Comment by gomex** [comment]
Ambos os fornecedores tem planos especiais para projeto opensource:

https://www.netlify.com/legal/open-source-policy
https://vercel.com/pricing

Acho que vale falar com os dois e ver qual responde ;)

**Comment by emersonsdo** [comment]
@gomex entendo que o SSR sim bastante importante, então deve ser algo bem relevante na nossa avaliação. 

Sendo assim, além dessas informações levantadas sobre SSR em geral, complemento com informações sobre o suporte ao SSR especificamente utilizando o Nextjs.

Na Vercel o processo é bastante transparente (e aqui o fato de terem sido eles os criadores no Next faz diferença): [https://vercel.com/docs/next.js/overview#no-configuration-required](https://vercel.com/docs/next.js/overview#no-configuration-required)

Já na Netlify é possível [ver aqui] (https://www.netlify.com/with/nextjs/), mas requer algumas configurações específicas para o funcionamento do SSR:
[https://github.com/netlify/next-on-netlify] (https://github.com/netlify/next-on-netlify)

Nesse aspecto então a Vercel teria vantagens.  Mas caso as tratativas para a hospedagem gratuita não andem na Vercel, a Netlify ainda seria uma alternativa.

Próximo passo é justamente conversar com eles sobre isso.

**Comment by emersonsdo** [comment]
Com ajuda de  @anapaulagomes e @guilhermelowa, criamos o texto para o pedido de hospedagem gratuito na Vercel. O pedido foi enviado hoje, aviso assim que houver retorno.
Acho que o melhor é aguardar, e só procurar a Netlify em caso de negativa da Vercel.

**Comment by emersonsdo** [comment]
Já tem uma semana que mandei o pedido para a Vercel e ainda não retornaram. Acham que é hora de mandar novamente ou algo do tipo? @anapaulagomes @guilhermelowa @gomex

**Comment by anapaulagomes** [comment]
Eu acho que demora mesmo, @emersonsdo. Esperaria mais um pouco, até porque não temos nada urgente e nem com funcionalidades do plano pago pra deployar. Pelo que vi, o que tem no plano gratuito já daria pra começar. Mas podemos também aplicar para o Netflix e ver o que rola. O que acha?

**Comment by emersonsdo** [comment]
Beleza, vamos aguardar hehehe. Durante essa semana eu mando o pedido pra Netlify - desconfio que a Netflix não vai poder nos ajudar =P

**Comment by anapaulagomes** [comment]
😂 eu loka @emersonsdo Valeeeu!

**Comment by anapaulagomes** [comment]
@emersonsdo conseguiu contato com a Netlify?

**Comment by emersonsdo** [comment]
Eita @anapaulagomes, na verdade admito que nem tentei =/
Mas vou tentar até semana que vem ou admitir minha derrota rs.

**Comment by emersonsdo** [comment]
@anapaulagomes posso colocar o email dadosabertosdefeira+site@gmail.com associado com essa conta da Netlify?
Precisaremos de um link para a página deles em nossa página principal: "Must feature a link to our service on your main page, or all internal pages", e aí no formulário é solicitado esse link. Ele dá a opção de usar algum badge já pronto, acho que é a melhor opção, pode ser?
Outra coisinha é que ele pergunta qual a licença do projeto, e eu não achei no nosso git, nem no portal, nem no meduim, você sabe onde encontro essa informação? E assim, mesmo que tenha sido incompetência minha, talvez seja bom dar mais visibilidade a essa informação, colocando nos guias e readme's, por exemplo.

**Comment by anapaulagomes** [comment]
Pode sim, claro!
A licença está faltando mesmo. Vou adicionar a MIT por aqui (a padrão que temos usado até agora).

Obrigada, @emersonsdo!

**Comment by emersonsdo** [comment]
@anapaulagomes, projeto submetido. Só fica de olho no e-mail dadosabertosdefeira@gmail.com, porque se der certo é ele quem vai estar associado a nossa conta ;)

**Comment by anapaulagomes** [comment]
Pode deixar! Qualquer novidade eu aviso! 👍🏽

**Comment by anapaulagomes** [comment]
Conseguimos com a Netlify! 🎉 Obrigada, @emersonsdo!

**Comment by emersonsdo** [comment]
Bom demais =)
