### ISSUE TITLE
Criar espaço para exibir apoiadores

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/portal#38]
Atualmente temos os seguintes apoiadores:

### Financiamento e Prêmios

* ShuttleworthFoundation
  * Logo: https://github.com/ShuttleworthFoundation/Logos/blob/master/Shuttleworth%20Funded/Shuttleworth%20Funded%20RGB/Shuttleworth%20Funded.jpg
  * Link: https://shuttleworthfoundation.org/
* Chamada para produção de podcast Tramas Democráticas - Goethe-Institut
  * Logo: https://www.goethe.de/resources/files/png90/goethe-site_5001-formatkey-png-default.png
  * Link: https://www.goethe.de/ins/br/pt/kul/sup/trd/edi.html

### Apoio

* Absam
  * Logo: https://absam.io/img/logo1.png
  * Link: https://absam.io/
* 1password
  * Logo: https://logodix.com/logo/2143906.png (pode cortar a seta de download)
  * Link: https://github.com/1Password/1password-teams-open-source
* Netlify
  * Logo: https://download.logo.wine/logo/Netlify/Netlify-Logo.wine.png
  * Link: https://www.netlify.com/open-source/
* Jetbrains
  * Logo: https://www.jetbrains.com/company/press/#images-logos
  * Link: https://www.jetbrains.com/?from=DadosAbertosDeFeira

### Apoio institucional

* Programa de Pós-Graduação em Ciência de Computação da UEFS
  * Logo: https://pbs.twimg.com/profile_images/1271555532491575296/2gDRxPZy_400x400.jpg (aguardando envio da com fundo transparente)
  * Link: https://pgcc.uefs.br/

**Comment by anapaulagomes** [comment]
* ShuttleworthFoundation
https://github.com/ShuttleworthFoundation/Logos/blob/master/Shuttleworth%20Funded/Shuttleworth%20Funded%20RGB/Shuttleworth%20Funded.jpg

**Comment by anapaulagomes** [comment]
Podemos colocar dentro de "Sobre".

**Comment by anapaulagomes** [comment]
@Naty_costa_design

**Comment by matheusrocha89** [comment]
Tendo o design da tela eu já implemento e abro o PR. Quero ir matando todas essas issues pequenas e rápidas logo, assim vai dando uma motivada em mim e no pessoal 😄
