### ISSUE TITLE
Enviar mensagem

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/portal#52]
**Como** cidadão,
**Eu quero** enviar uma mensagem para o projeto,
**Assim eu** posso tirar dúvidas ou entrar em contato quando necessário.

### Critérios de aceitação

- [x] Receber a mensagem do usuário (campo obrigatório)
- [x] Ter campos de nome, telefone ou e-mail (sendo nome e e-mail obrigatórios)
- [x] Configurar formulário pelo Netlify

### Notas

Atualmente já temos um formulário mas precisamos fazer alguns ajustes nele.

Bugfix:

- [x] Não mudar de página ao enviar uma mensagem - apenas mostrar uma confirmação de envio

**Comment by matheusrocha89** [comment]
Ok, eu consigo fazer isso hoje. Deixa comigo, mais tarde abro um PR 👍 
Estou on 🔥  😄
