### ISSUE TITLE
Adicionar seção para projetos

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/portal#66]
**Como** cidadão,
**Eu gostaria** de saber quais projetos são tocados pelo Dados Abertos de Feira,
**Assim eu** posso conhecer melhor a iniciativa e ver com quais projetos eu me identifico.

### Critérios de aceitação

- [x] Uma seção no site com os nossos projetos
- [ ] Para cada projeto, precisamos ter um ícone, o nome, uma descrição simples e o link
- [ ] Para projetos em andamento deixar a logo cinza
- [x] Opcional: seria interessante ter tags

### Notas

Lista de projetos (construção em andamento 😅)

* Maria Quitéria (tags: raspagem de dados, busca de dados)
* Bot do Diário Oficial (tags: bot, twitter)
* Podcast Cidades Abertas (tags: podcast)
* Empacotador (tags: publicação de dados)

**Comment by anapaulagomes** [comment]
Figma atualizado 🎉  Obrigada @exageraldo!

https://www.figma.com/file/N5W39QxGzk4P4kQnMblTzs/DadosFeira-(Copy---cassiano)?node-id=976%3A2484

**Comment by exageraldo** [comment]
Que nada! 😃
Gostaria de agradecer ao @lucascassiano pelo pareamento e paciência.
Aprendi muuuuito mesmo! 🤗
