### ISSUE TITLE
Versão mobile para o MVP atual

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/portal#8]
Segundo pesquisa do Cetic.br em 2019, [61% das pessoas não possuem computador em casa](https://cetic.br/pt/tics/domicilios/2019/domicilios/A1/) e [apenas 37% tem computador e internet em casa](https://cetic.br/pt/tics/domicilios/2019/domicilios/A4B/).
Quando observamos o recorte por classe social, vemos que 20 milhões de domicílios não possuem Internet (28%), sendo que dessa fatia, 50% nas classes DE. O celular é o dispositivo mais usado (99%); 58% acessam a Internet somente pelo celular, com destaque para a área rural (79%) e classes DE (85%) concentram uso exclusivo.
Fonte: https://cetic.br/media/analises/tic_domicilios_2019_coletiva_imprensa.pdf

O Dados é um projeto para todos e devemos traduzir esse discurso em ações, criando soluções que permitam que qualquer pessoa possa usar a plataforma de maneira rápido e fácil, tendo oportunidade de acesso iguais, independente da classe ou condição física. Por isso, precisamos pensar em _mobile first_ e começar certo desde o começo. :)

**Comment by andrecostta** [comment]
Já comecei a trabalhar no MVP e temos algumas telas prontas.
Hoje alinhamos sobre a busca fixa no menu e prováveis mudanças no "Não encontro o que queria".

**Comment by andrecostta** [comment]
https://www.figma.com/file/XNfcVKFQLMcw4WzYB9srDs/DadosFeira?node-id=224%3A2144
Link do protótipo.

**Comment by filipebsmaia** [comment]
Estou trabalhando nessa implementação, aproveitando e fazendo já a versão desktop.
